Repository familymoments/family-moments-android, pull requests merged in 2024-07, with the labels that each got.

#134 #129 [마이페이지] 가족 설정 - 가족 강퇴시키기
  app/src/main/java/io/familymoments/app/core/graph/Route.kt
  app/src/main/java/io/familymoments/app/core/graph/getMainGraph.kt
  app/src/main/java/io/familymoments/app/core/network/HttpResponse.kt
  app/src/main/java/io/familymoments/app/core/network/api/FamilyService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/GetFamilyNameResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/SearchMemberResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/FamilyRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/FamilyRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/viewmodel/MainViewModel.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/graph/FamilySettingGraph.kt
  app/src/main/java/io/familymoments/app/feature/removemember/RemoveFamilyMemberPopup.kt
  app/src/main/java/io/familymoments/app/feature/removemember/screen/RemoveFamilyMemberConfirmScreen.kt
  app/src/main/java/io/familymoments/app/feature/removemember/screen/RemoveFamilyMemberScreen.kt
  app/src/main/java/io/familymoments/app/feature/removemember/uistate/RemoveFamilyMemberConfirmUiState.kt
  app/src/main/java/io/familymoments/app/feature/removemember/uistate/RemoveFamilyMemberUiState.kt
  app/src/main/java/io/familymoments/app/feature/removemember/viewmodel/RemoveFamilyMemberConfirmViewModel.kt
  app/src/main/java/io/familymoments/app/feature/removemember/viewmodel/RemoveFamilyMemberViewModel.kt
  app/src/main/java/io/familymoments/app/feature/splash/screen/SplashScreen.kt
  app/src/main/java/io/familymoments/app/feature/splash/viewmodel/SplashViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#139 #138 [2차 QA] 코비 담당 이슈 리스트
  app/src/main/java/io/familymoments/app/core/base/BaseViewModel.kt
  app/src/main/java/io/familymoments/app/core/component/FMButton.kt
  app/src/main/java/io/familymoments/app/core/component/ImageSelectionMenu.kt
  app/src/main/java/io/familymoments/app/core/component/PostDropdownMenu.kt
  app/src/main/java/io/familymoments/app/core/component/PostDropdownMenu2.kt
  app/src/main/java/io/familymoments/app/core/component/PostItem.kt
  app/src/main/java/io/familymoments/app/core/component/SignUpTextFieldArea.kt
  app/src/main/java/io/familymoments/app/core/component/popup/CompletePopUp.kt
  app/src/main/java/io/familymoments/app/core/component/popup/DeletePopUp.kt
  app/src/main/java/io/familymoments/app/core/network/social/NaverAuth.kt
  app/src/main/java/io/familymoments/app/core/theme/AppColors.kt
  app/src/main/java/io/familymoments/app/core/util/Constants.kt
  app/src/main/java/io/familymoments/app/core/util/FileUtil.kt
  app/src/main/java/io/familymoments/app/feature/addpost/screen/AddPostScreen.kt
  app/src/main/java/io/familymoments/app/feature/addpost/viewmodel/AddPostViewModel.kt
  app/src/main/java/io/familymoments/app/feature/album/screen/AlbumScreen.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/screen/MainScreen.kt
  app/src/main/java/io/familymoments/app/feature/calendar/screen/CalendarDayScreen.kt
  app/src/main/java/io/familymoments/app/feature/calendar/screen/CalendarScreen.kt
  app/src/main/java/io/familymoments/app/feature/choosingfamily/component/ChoosingFamilyHeaderButtonLayout.kt
  app/src/main/java/io/familymoments/app/feature/choosingfamily/screen/ChoosingFamilyScreen.kt
  app/src/main/java/io/familymoments/app/feature/choosingfamily/screen/StartScreen.kt
  app/src/main/java/io/familymoments/app/feature/deleteaccount/screen/DeleteAccountScreen.kt
  app/src/main/java/io/familymoments/app/feature/familyinvitationlink/screen/FamilyInvitationLinkScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/FindIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/ForgotIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/VerifyIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ForgotPasswordScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/IdentifyScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ResetScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/VerifyPwdScreen.kt
  app/src/main/java/io/familymoments/app/feature/home/screen/HomeScreen.kt
  app/src/main/java/io/familymoments/app/feature/login/screen/LoginScreen.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/screen/ModifyFamilyInfoScreen.kt
  app/src/main/java/io/familymoments/app/feature/modifypassword/screen/ModifyPasswordScreen.kt
  app/src/main/java/io/familymoments/app/feature/mypage/component/LogoutPopup.kt
  app/src/main/java/io/familymoments/app/feature/mypage/screen/MyPageScreen.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileEditScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileViewScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpItems.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SocialSignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/transferpermission/screen/TransferPermissionScreen.kt
Labels: 🛠️ 버그 수정, 🔧 refactor

#136 #135 [마이페이지] 가족 설정 - 가족 탈퇴하기
  app/src/main/java/io/familymoments/app/core/component/popup/CompletePopUp.kt
  app/src/main/java/io/familymoments/app/core/network/api/FamilyService.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSource.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/core/network/repository/FamilyRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/FamilyRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/graph/FamilySettingGraph.kt
  app/src/main/java/io/familymoments/app/feature/leavefamily/screen/LeaveFamilyScreen.kt
  app/src/main/java/io/familymoments/app/feature/leavefamily/uistate/LeaveFamilyUiState.kt
  app/src/main/java/io/familymoments/app/feature/leavefamily/viewmodel/LeaveFamilyViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#143 #142 [2차 QA] 토미 담당 이슈 리스트
  app/src/main/java/io/familymoments/app/feature/choosingfamily/screen/ChoosingFamilyScreen.kt
  app/src/main/java/io/familymoments/app/feature/creatingfamily/component/GalleryOrDefaultImageSelectButton.kt
  app/src/main/java/io/familymoments/app/feature/creatingfamily/screen/SetProfileScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ResetScreen.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/screen/ModifyFamilyInfoScreen.kt
  app/src/main/res/drawable/default_family_profile.png
  app/src/main/res/values/strings.xml
Labels: 🛠️ 버그 수정

#141 [2차 QA] 베리 담당 이슈 리스트
  app/src/main/java/io/familymoments/app/core/component/PostDropdownMenu.kt
  app/src/main/java/io/familymoments/app/core/component/PostDropdownMenu2.kt
  app/src/main/java/io/familymoments/app/core/component/PostItem.kt
  app/src/main/java/io/familymoments/app/core/component/popup/FailPopUp.kt
  app/src/main/java/io/familymoments/app/core/component/popup/ReportPopUp.kt
  app/src/main/java/io/familymoments/app/core/graph/getMainGraph.kt
  app/src/main/java/io/familymoments/app/core/network/api/CommentService.kt
  app/src/main/java/io/familymoments/app/core/network/api/PostService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/ReportRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/GetPostLovesResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/CommentRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/PostRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/CommentRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/PostRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/calendar/screen/CalendarDayScreen.kt
  app/src/main/java/io/familymoments/app/feature/calendar/viewmodel/CalendarDayViewModel.kt
  app/src/main/java/io/familymoments/app/feature/home/screen/HomeScreen.kt
  app/src/main/java/io/familymoments/app/feature/home/uistate/HomeUiState.kt
  app/src/main/java/io/familymoments/app/feature/home/viewmodel/HomeViewModel.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/uistate/PostDetailUiState.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️ 버그 수정

#147 #145 코비 2차 QA 추가 수정
  app/src/main/java/io/familymoments/app/feature/addpost/viewmodel/AddPostViewModel.kt
  app/src/main/java/io/familymoments/app/feature/choosingfamily/screen/StartScreen.kt
  app/src/main/java/io/familymoments/app/feature/login/screen/LoginScreen.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
Labels: 🛠️ 버그 수정

#146 #144 [마이페이지] 가족 설정 - 가족 삭제하기
  app/src/main/java/io/familymoments/app/core/component/FMTextField.kt
  app/src/main/java/io/familymoments/app/core/graph/Route.kt
  app/src/main/java/io/familymoments/app/core/graph/getMainGraph.kt
  app/src/main/java/io/familymoments/app/core/network/api/FamilyService.kt
  app/src/main/java/io/familymoments/app/core/network/repository/FamilyRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/FamilyRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/util/ScaffoldState.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/screen/MainScreen.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/viewmodel/MainViewModel.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/graph/DeleteFamilyGraph.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/screen/DeleteFamilyCompleteScreen.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/screen/DeleteFamilyScreen.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/screen/EnterFamilyNameScreen.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/uistate/DeleteFamilyUiState.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/uistate/EnterFamilyNameUiState.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/viewmodel/DeleteFamilyViewModel.kt
  app/src/main/java/io/familymoments/app/feature/deletefamily/viewmodel/EnterFamilyNameViewModel.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/FamilySettingNavItem.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/graph/FamilySettingGraph.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능
