Repository familymoments/family-moments-android, pull requests merged in 2024-06, with the labels that each got.

#107 [비밀번호 찾기] 비밀번호 찾기 화면 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/familymoments/app/core/component/FMButton.kt
  app/src/main/java/io/familymoments/app/core/component/popup/CompletePopUp.kt
  app/src/main/java/io/familymoments/app/core/network/api/UserService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/CheckIdExistRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/FindPwdRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/ModifyPwdInFindPwdRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/SendEmailRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/CheckIdExistResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/FindPwdResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/ModifyPwdInFindPwdResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/SendEmailResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/activity/ForgotPasswordActivity.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/graph/ForgotPasswordGraph.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ForgotPasswordScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/IdentifyScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ResetScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/VerifyScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/uistate/IdentifyUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/uistate/ResetUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/uistate/VerifyUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/ForgotPasswordSharedViewModel.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/ForgotPasswordViewModel.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/IdentifyViewModel.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/ResetViewModel.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/VerifyViewModel.kt
  app/src/main/java/io/familymoments/app/feature/login/screen/LoginScreen.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#110 [소셜 로그인] 카카오, 네이버 로그인 추가
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/familymoments/app/FamilyMomentsApplication.kt
  app/src/main/java/io/familymoments/app/core/component/FMTextField.kt
  app/src/main/java/io/familymoments/app/core/component/SignUpTextFieldArea.kt
  app/src/main/java/io/familymoments/app/core/network/AuthInterceptor.kt
  app/src/main/java/io/familymoments/app/core/network/api/SignInService.kt
  app/src/main/java/io/familymoments/app/core/network/api/UserService.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSource.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/SignUpRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/SocialSignInRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/ApiResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/LoginResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/SocialSignInResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/SignInRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/SignInRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/social/KakaoAuth.kt
  app/src/main/java/io/familymoments/app/core/network/social/NaverAuth.kt
  app/src/main/java/io/familymoments/app/core/theme/Theme.kt
  app/src/main/java/io/familymoments/app/di/AppModule.kt
  app/src/main/java/io/familymoments/app/di/RepositoryModule.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/VerifyScreen.kt
  app/src/main/java/io/familymoments/app/feature/login/activity/LoginActivity.kt
  app/src/main/java/io/familymoments/app/feature/login/screen/LoginScreen.kt
  app/src/main/java/io/familymoments/app/feature/login/uistate/LoginUiState.kt
  app/src/main/java/io/familymoments/app/feature/login/viewmodel/LoginViewModel.kt
  app/src/main/java/io/familymoments/app/feature/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/io/familymoments/app/feature/signup/activity/SignUpActivity.kt
  app/src/main/java/io/familymoments/app/feature/signup/activity/SocialSignUpActivity.kt
  app/src/main/java/io/familymoments/app/feature/signup/mapper/SignUpRequestMapper.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpItems.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SocialSignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/uistate/SignUpUiState.kt
  app/src/main/java/io/familymoments/app/feature/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable/ic_google_login.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  image/image.sh
  settings.gradle.kts
Labels: ⭐️ 새로운 기능, 🔧 refactor

#112 #109 [마이페이지] 가족 설정 - 가족 정보 수정
  app/src/main/java/io/familymoments/app/core/component/ImageSelectionMenu.kt
  app/src/main/java/io/familymoments/app/core/network/api/FamilyService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/GetFamilyNameResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/FamilyRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/FamilyRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/util/EventManager.kt
  app/src/main/java/io/familymoments/app/core/util/FileUtil.kt
  app/src/main/java/io/familymoments/app/di/AppModule.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/screen/MainScreen.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/uistate/AppBarUiState.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/viewmodel/MainViewModel.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/graph/FamilySettingGraph.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/model/ModifyFamilyInfoRequest.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/screen/ModifyFamilyInfoScreen.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/uistate/ModifyFamilyInfoUiState.kt
  app/src/main/java/io/familymoments/app/feature/modifyfamilyInfo/viewmodel/ModifyFamilyInfoViewModel.kt
  app/src/main/java/io/familymoments/app/feature/profile/viewmodel/ProfileEditViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#120 #116 [마이페이지] 프로필 변경 화면 이미지 관련 로직 수정
  app/src/main/java/io/familymoments/app/core/component/FMDropdownMenu.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileEditScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/uistate/ProfileEditUiState.kt
  app/src/main/java/io/familymoments/app/feature/profile/viewmodel/ProfileEditViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ 버그 수정

#114 #111 [아이디 찾기 화면] 아이디 찾기 화면 개발 및 api 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/familymoments/app/core/component/FMButton.kt
  app/src/main/java/io/familymoments/app/core/network/api/UserService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/FindIdRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/FindIdResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/uistate/SendEmailUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/activity/ForgotIdActivity.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/graph/ForgotIdGraph.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/FindIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/ForgotIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/screen/VerifyIdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/uistate/VerifyIdUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotid/viewmodel/VerifyIdViewModel.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/graph/ForgotPasswordGraph.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/IdentifyScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/ResetScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/screen/VerifyPwdScreen.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/uistate/VerifyPwdUiState.kt
  app/src/main/java/io/familymoments/app/feature/forgotpassword/viewmodel/VerifyPwdViewModel.kt
  app/src/main/java/io/familymoments/app/feature/login/activity/LoginActivity.kt
  app/src/main/java/io/familymoments/app/feature/login/screen/LoginScreen.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#118 #117 [글 상세 화면] 댓글 작성 시간 시차 수정
  app/src/main/java/io/familymoments/app/core/viewmodel/PostItemViewModel.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
Labels: 🛠️ 버그 수정

#123 #122 [회원가입 화면] 회원가입 화면의 버그를 수정한다.
  app/src/main/java/io/familymoments/app/core/network/dto/response/SignUpResponse.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/viewmodel/SignUpViewModel.kt
Labels: 🛠️ 버그 수정

#125 #124 [캘린더] 게시물 리스트가 비어있는 경우 minPostId 갱신 로직 수정
  app/src/main/java/io/familymoments/app/feature/album/viewmodel/AlbumViewModel.kt
  app/src/main/java/io/familymoments/app/feature/calendar/uistate/CalendarDayUiState.kt
  app/src/main/java/io/familymoments/app/feature/calendar/viewmodel/CalendarDayViewModel.kt
  app/src/main/java/io/familymoments/app/feature/home/viewmodel/HomeViewModel.kt
Labels: 🛠️ 버그 수정

#128 #126 [마이페이지] 가족 설정 - 가족 권한 넘기기
  app/src/main/java/io/familymoments/app/core/component/popup/CompletePopUp.kt
  app/src/main/java/io/familymoments/app/core/network/api/FamilyService.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/TransferPermissionRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/FamilyPermission.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/TransferPermissionResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/FamilyRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/FamilyRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/familysettings/graph/FamilySettingGraph.kt
  app/src/main/java/io/familymoments/app/feature/transferpermission/screen/TransferPermissionScreen.kt
  app/src/main/java/io/familymoments/app/feature/transferpermission/uistate/TransferPermissionUiState.kt
  app/src/main/java/io/familymoments/app/feature/transferpermission/viewmodel/TransferPermissionViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#96 #95 [홈 화면] 게시글 하트 반영 안되는 문제
  app/src/main/java/io/familymoments/app/core/component/PostItem.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/GetPostsResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/PostRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/calendar/screen/CalendarDayScreen.kt
  app/src/main/java/io/familymoments/app/feature/calendar/viewmodel/CalendarDayViewModel.kt
  app/src/main/java/io/familymoments/app/feature/home/screen/HomeScreen.kt
  app/src/main/java/io/familymoments/app/feature/home/viewmodel/HomeViewModel.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/uistate/PostDetailUiState.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
Labels: 🛠️ 버그 수정

#130 #127 [마이페이지] 회원 탈퇴 구현
  app/src/main/java/io/familymoments/app/core/network/api/UserService.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSource.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/social/KakaoAuth.kt
  app/src/main/java/io/familymoments/app/core/network/social/NaverAuth.kt
  app/src/main/java/io/familymoments/app/feature/deleteaccount/screen/DeleteAccountScreen.kt
  app/src/main/java/io/familymoments/app/feature/deleteaccount/uistate/DeleteAccountUiState.kt
  app/src/main/java/io/familymoments/app/feature/deleteaccount/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/io/familymoments/app/feature/mypage/graph/MyPageGraph.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#133 #132 자동 로그인 구현
  app/build.gradle.kts
  app/src/main/java/io/familymoments/app/core/network/LoginType.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSource.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/UserProfileResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/core/network/social/KakaoAuth.kt
  app/src/main/java/io/familymoments/app/core/network/social/NaverAuth.kt
  app/src/main/java/io/familymoments/app/feature/deleteaccount/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/io/familymoments/app/feature/login/viewmodel/LoginViewModel.kt
  app/src/main/java/io/familymoments/app/feature/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/io/familymoments/app/feature/splash/activity/SplashActivity.kt
  app/src/main/java/io/familymoments/app/feature/splash/screen/SplashScreen.kt
  app/src/main/java/io/familymoments/app/feature/splash/viewmodel/SplashViewModel.kt
  gradle/libs.versions.toml
Labels: ⭐️ 새로운 기능, 🔧 refactor
