Repository familymoments/family-moments-android, pull requests merged in 2024-09, with the labels that each got.

#165 #119 [회원가입 화면] 회원가입 수정 사항 반영
  app/src/main/java/io/familymoments/app/core/component/LoadingIndicator.kt
  app/src/main/java/io/familymoments/app/core/component/SignUpTextFieldArea.kt
  app/src/main/java/io/familymoments/app/core/graph/Route.kt
  app/src/main/java/io/familymoments/app/core/network/api/SignInService.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/ProfileEditRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/SendEmailVerificationCodeRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/SignUpRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/request/VerifyEmailVerificationCodeRequest.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/LoginResponse.kt
  app/src/main/java/io/familymoments/app/core/network/dto/response/UserProfileResponse.kt
  app/src/main/java/io/familymoments/app/core/network/repository/SignInRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/SignInRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/login/activity/LoginActivity.kt
  app/src/main/java/io/familymoments/app/feature/login/viewmodel/LoginViewModel.kt
  app/src/main/java/io/familymoments/app/feature/profile/graph/ProfileGraph.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileEditScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileViewScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/uistate/ProfileEditUiState.kt
  app/src/main/java/io/familymoments/app/feature/profile/viewmodel/ProfileEditViewModel.kt
  app/src/main/java/io/familymoments/app/feature/signup/UserInfoFormatChecker.kt
  app/src/main/java/io/familymoments/app/feature/signup/activity/SocialSignUpActivity.kt
  app/src/main/java/io/familymoments/app/feature/signup/mapper/SignUpRequestMapper.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpItems.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SocialSignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/uistate/SignUpUiState.kt
  app/src/main/java/io/familymoments/app/feature/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능, 🔧 refactor

#162 [#160] 앱 아이콘 변경, 서비스 이용약관, 개인정보 처리방침 링크 추가
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/io/familymoments/app/core/util/Constants.kt
  app/src/main/java/io/familymoments/app/feature/mypage/MyPageItem.kt
  app/src/main/java/io/familymoments/app/feature/mypage/screen/MyPageScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpItems.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/screen/SocialSignUpScreen.kt
  app/src/main/java/io/familymoments/app/feature/signup/uistate/SignUpUiState.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#163 #159 [홈 화면] 유저 신고
  app/src/main/java/io/familymoments/app/core/component/ReportUserPopup.kt
  app/src/main/java/io/familymoments/app/core/component/popup/DeletePopUp.kt
  app/src/main/java/io/familymoments/app/core/network/api/UserService.kt
  app/src/main/java/io/familymoments/app/core/network/repository/UserRepository.kt
  app/src/main/java/io/familymoments/app/core/network/repository/impl/UserRepositoryImpl.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/screen/MainScreen.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/uistate/AppBarUiState.kt
  app/src/main/java/io/familymoments/app/feature/bottomnav/viewmodel/MainViewModel.kt
  app/src/main/java/io/familymoments/app/feature/mypage/screen/MyPageScreen.kt
  app/src/main/res/drawable/ic_report_user.xml
  app/src/main/res/values/strings.xml
Labels: ⭐️ 새로운 기능

#166 #161 [마이페이지] 프로필 조회, 수정 - 생년월일, 이름 삭제
  app/src/main/java/io/familymoments/app/core/graph/Route.kt
  app/src/main/java/io/familymoments/app/core/network/datasource/UserInfoPreferencesDataSourceImpl.kt
  app/src/main/java/io/familymoments/app/feature/profile/graph/ProfileGraph.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileEditScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/screen/ProfileViewScreen.kt
  app/src/main/java/io/familymoments/app/feature/profile/uistate/ProfileEditUiState.kt
  app/src/main/java/io/familymoments/app/feature/profile/viewmodel/ProfileEditViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🚨 버그가 있어요, 🔧 refactor

#170 [posts API] createdAt 필드의 시간 형식 변경에 따른 수정
  app/src/main/java/io/familymoments/app/core/component/PostItem.kt
  app/src/main/java/io/familymoments/app/core/util/DateExtension.kt
  app/src/main/java/io/familymoments/app/core/util/DateFormatter.kt
  app/src/main/java/io/familymoments/app/feature/calendar/viewmodel/CalendarDayViewModel.kt
  app/src/main/java/io/familymoments/app/feature/home/viewmodel/HomeViewModel.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/screen/PostDetailScreen.kt
  app/src/main/java/io/familymoments/app/feature/postdetail/viewmodel/PostDetailViewModel.kt
Labels: 🛠️ 버그 수정
